#!/usr/bin/env python3
"""Regenerate ``src/hop_core/dita/_classes.py`` from the bundled OASIS DTDs.

Source DITA rarely carries ``@class`` attributes — a DTD-aware parser adds them
as defaults, and hop-core deliberately parses without loading the DTD (the
DITA 1.3 grammars exceed lxml's entity-amplification limit). The renderer
dispatches on ``@class`` the way DITA-OT does, so it needs the defaults the DTD
would have supplied. This script extracts every ``<!ATTLIST name %global-atts;
class CDATA "...">`` declaration from the bundled ``.mod`` files.

Run from the repo root after updating the bundled grammars:

    python3 scripts/generate_dita_classes.py
"""

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DTD_DIR = REPO_ROOT / "src/hop_core/dita/resources/org.oasis-open.dita.v1_3/dtd"
OUTPUT = REPO_ROOT / "src/hop_core/dita/_classes.py"

ATTLIST = re.compile(
    r'<!ATTLIST\s+([A-Za-z_][\w.-]*)\s+%global-atts;\s+class\s+CDATA\s+"([^"]*)"'
)


def collect() -> dict:
    classes: dict = {}
    for mod in sorted(DTD_DIR.rglob("*.mod")):
        for name, value in ATTLIST.findall(mod.read_text(encoding="utf-8")):
            value = " ".join(value.split())
            existing = classes.get(name)
            if existing and existing != value:
                # Only map/topic twins collide (shortdesc, linktext, searchtitle);
                # the renderer handles topics, so the topic declaration wins.
                if " topic/" in f" {existing} ":
                    continue
                if " topic/" not in f" {value} ":
                    raise SystemExit(f"Conflicting @class for <{name}>: {existing!r} vs {value!r}")
            classes[name] = value
    return classes


def main() -> None:
    classes = collect()
    lines = [
        '"""Default DITA 1.3 ``@class`` values, keyed by element name.',
        "",
        "GENERATED by scripts/generate_dita_classes.py from the bundled OASIS DTDs.",
        "Do not edit by hand.",
        '"""',
        "",
        "DEFAULT_CLASSES = {",
    ]
    for name in sorted(classes):
        lines.append(f"    {name!r}: {(' ' + classes[name] + ' ')!r},")
    lines.append("}")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(classes)} element classes to {OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
